using BotNet.CommandHandlers.AI.RateLimit;
using Mediator;
using BotNet.Commands;
using BotNet.Commands.AI.OpenAI;
using BotNet.Commands.BotUpdate.Message;
using BotNet.Commands.ChatAggregate;
using BotNet.Commands.CommandPrioritization;
using BotNet.Commands.SenderAggregate;
using BotNet.Services.MarkdownV2;
using BotNet.Services.OpenAI;
using BotNet.Services.OpenAI.Models;
using BotNet.Services.RateLimit;
using BotNet.Services.TelegramClient;
using Microsoft.Extensions.Logging;
using Telegram.Bot;
using Telegram.Bot.Types;
using Telegram.Bot.Types.Enums;
using Telegram.Bot.Types.ReplyMarkups;

namespace BotNet.CommandHandlers.AI.OpenAI {
	public sealed class AskCommandHandler(
		ITelegramBotClient telegramBotClient,
		OpenAiClient openAiClient,
		ITelegramMessageCache telegramMessageCache,
		CommandPriorityCategorizer commandPriorityCategorizer,
		ILogger<AskCommandHandler> logger
	) : ICommandHandler<AskCommand> {
		public async ValueTask<Unit> Handle(AskCommand askCommand, CancellationToken cancellationToken) {
			if (askCommand.Command.Chat is GroupChat) {
				try {
					AiRateLimiters.GroupChatRateLimiter.ValidateActionRate(
						chatId: askCommand.Command.Chat.Id,
						userId: askCommand.Command.Sender.Id
					);
				} catch (RateLimitExceededException exc) {
					await telegramBotClient.SendMessage(
						chatId: askCommand.Command.Chat.Id,
						text: $"<code>Anda terlalu banyak memanggil AI. Coba lagi {exc.Cooldown} atau lanjutkan di private chat.</code>",
						parseMode: ParseMode.Html,
						replyParameters: new ReplyParameters {
							MessageId = askCommand.Command.MessageId
						},
						replyMarkup: new InlineKeyboardMarkup(
							InlineKeyboardButton.WithUrl("Private chat 💬", "t.me/TeknumBot")
						),
						cancellationToken: cancellationToken
					);
				}
			} else {
				try {
					OpenAiTextPromptHandler.ChatRateLimiter.ValidateActionRate(
						chatId: askCommand.Command.Chat.Id,
						userId: askCommand.Command.Sender.Id
					);
				} catch (RateLimitExceededException exc) {
					await telegramBotClient.SendMessage(
						chatId: askCommand.Command.Chat.Id,
						text: $"<code>Anda terlalu banyak memanggil AI. Coba lagi {exc.Cooldown}.</code>",
						parseMode: ParseMode.Html,
						replyParameters: new ReplyParameters {
							MessageId = askCommand.Command.MessageId
						},
						cancellationToken: cancellationToken
					);
					return default;
				}
			}

			// Fire and forget
			BackgroundTask.Run(async () => {
				List<ChatMessage> messages = [
					ChatMessage.FromText("system", "The following is a conversation with an AI assistant. The assistant is helpful, creative, direct, concise, and always get to the point."),
					ChatMessage.FromText("user", askCommand.Prompt)
				];

				messages.AddRange(
					from message in askCommand.Thread.Take(10).Reverse()
					select ChatMessage.FromText(
						role: message.Sender.ChatGptRole,
						text: message.Text
					)
				);

				Message responseMessage = await telegramBotClient.SendMessage(
					chatId: askCommand.Command.Chat.Id,
					text: MarkdownV2Sanitizer.Sanitize("… ⏳"),
					parseMode: ParseMode.MarkdownV2,
					replyParameters: new ReplyParameters {
						MessageId = askCommand.Command.MessageId
					}
				);

				string response = await openAiClient.ChatAsync(
					model: askCommand switch {
						({ Command: { Sender: VipSender } or { Chat: HomeGroupChat } }) => "gpt-4-1106-preview",
						_ => "gpt-3.5-turbo"
					},
					messages: messages,
					maxTokens: 512,
					cancellationToken: cancellationToken
				);

				// Finalize message
				try {
					responseMessage = await telegramBotClient.EditMessageTextAsync(
						chatId: askCommand.Command.Chat.Id,
						messageId: responseMessage.MessageId,
						text: response,
						parseModes: [ParseMode.MarkdownV2, ParseMode.Markdown, ParseMode.Html],
						replyMarkup: new InlineKeyboardMarkup(
							InlineKeyboardButton.WithUrl(
								text: askCommand switch {
									({ Command: { Sender: VipSender } or { Chat: HomeGroupChat } }) => "Generated by OpenAI GPT-4",
									_ => "Generated by OpenAI GPT-3.5 Turbo"
								},
								url: "https://openai.com/gpt-4"
							)
						),
						cancellationToken: cancellationToken
					);
				} catch (Exception exc) {
					logger.LogError(exc, null);
					await telegramBotClient.EditMessageText(
						chatId: askCommand.Command.Chat.Id,
						messageId: responseMessage.MessageId,
						text: "😵",
						parseMode: ParseMode.Html,
						cancellationToken: cancellationToken
					);
				}

				// Track thread
				telegramMessageCache.Add(
					message: AiResponseMessage.FromMessage(
						message: responseMessage,
						replyToMessage: askCommand.Command,
						callSign: "GPT",
						commandPriorityCategorizer: commandPriorityCategorizer
					)
				);
			}, logger);
	return default;
		}
	}
}
