using BotNet.Commands;
using Mediator;
using BotNet.Commands.AI.OpenAI;
using BotNet.Commands.BotUpdate.Message;
using BotNet.Commands.CommandPrioritization;
using BotNet.Services.OpenAI.Skills;
using Microsoft.Extensions.Logging;
using Telegram.Bot;
using Telegram.Bot.Types;
using Telegram.Bot.Types.Enums;
using Telegram.Bot.Types.ReplyMarkups;

namespace BotNet.CommandHandlers.AI.OpenAI {
	public sealed class OpenAiImageGenerationPromptHandler(
		ITelegramBotClient telegramBotClient,
		ImageGenerationBot imageGenerationBot,
		ITelegramMessageCache telegramMessageCache,
		CommandPriorityCategorizer commandPriorityCategorizer,
		ILogger<OpenAiImageGenerationPromptHandler> logger
	) : ICommandHandler<OpenAiImageGenerationPrompt> {
		public async ValueTask<Unit> Handle(OpenAiImageGenerationPrompt command, CancellationToken cancellationToken) {
			// Fire and forget
			BackgroundTask.Run(async () => {
				Uri generatedImageUrl;
				try {
					generatedImageUrl = await imageGenerationBot.GenerateImageAsync(
						prompt: command.Prompt,
						cancellationToken: cancellationToken
					);
				} catch (Exception exc) {
					logger.LogError(exc, "Could not generate image");
					await telegramBotClient.EditMessageText(
						chatId: command.Chat.Id,
						messageId: command.ResponseMessageId,
						text: "<code>Failed to generate image.</code>",
						parseMode: ParseMode.Html,
						cancellationToken: cancellationToken
					);
					return;
				}

				// Delete busy message
				try {
					await telegramBotClient.DeleteMessage(
						chatId: command.Chat.Id,
						messageId: command.ResponseMessageId,
						cancellationToken: cancellationToken
					);
				} catch (OperationCanceledException) {
					return;
				}

				// Send generated image
				Message responseMessage = await telegramBotClient.SendPhoto(
					chatId: command.Chat.Id,
					photo: new InputFileUrl(generatedImageUrl),
					replyMarkup: new InlineKeyboardMarkup(
						InlineKeyboardButton.WithUrl(
							text: "Generated by OpenAI DALL-E 3",
							url: "https://openai.com/dall-e-3"
						)
					),
					replyParameters: new ReplyParameters {
						MessageId = command.PromptMessageId
					},
					cancellationToken: cancellationToken
				);

				// Track thread
				telegramMessageCache.Add(
					NormalMessage.FromMessage(responseMessage, commandPriorityCategorizer)
				);
			}, logger);

			return default;
		}
	}
}
