using BotNet.Commands;
using Mediator;
using BotNet.Commands.AI.Stability;
using BotNet.Commands.BotUpdate.Message;
using BotNet.Commands.CommandPrioritization;
using BotNet.Services.Stability.Models;
using BotNet.Services.Stability.Skills;
using Microsoft.Extensions.Logging;
using Telegram.Bot;
using Telegram.Bot.Types;
using Telegram.Bot.Types.Enums;
using Telegram.Bot.Types.ReplyMarkups;

namespace BotNet.CommandHandlers.AI.Stability {
	public sealed class StabilityTextToImagePromptHandler(
		ITelegramBotClient telegramBotClient,
		ImageGenerationBot imageGenerationBot,
		ITelegramMessageCache telegramMessageCache,
		CommandPriorityCategorizer commandPriorityCategorizer,
		ILogger<StabilityTextToImagePromptHandler> logger
	) : ICommandHandler<StabilityTextToImagePrompt> {
		public async ValueTask<Unit> Handle(StabilityTextToImagePrompt command, CancellationToken cancellationToken) {
			// Fire and forget
			BackgroundTask.Run(async () => {
				byte[] generatedImage;
				try {
					generatedImage = await imageGenerationBot.GenerateImageAsync(
						prompt: command.Prompt,
						cancellationToken: cancellationToken
					);
				} catch (ContentFilteredException exc) {
					await telegramBotClient.EditMessageText(
						chatId: command.Chat.Id,
						messageId: command.ResponseMessageId,
						text: $"<code>{exc.Message}</code>",
						parseMode: ParseMode.Html,
						cancellationToken: cancellationToken
					);
					return;
				} catch {
					await telegramBotClient.EditMessageText(
						chatId: command.Chat.Id,
						messageId: command.ResponseMessageId,
						text: "<code>Failed to generate image.</code>",
						parseMode: ParseMode.Html,
						cancellationToken: cancellationToken
					);
					return;
				}

				// Delete busy message
				try {
					await telegramBotClient.DeleteMessage(
						chatId: command.Chat.Id,
						messageId: command.ResponseMessageId,
						cancellationToken: cancellationToken
					);
				} catch (OperationCanceledException) {
					return;
				}

				// Send generated image
				using MemoryStream generatedImageStream = new(generatedImage);
				Message responseMessage = await telegramBotClient.SendPhoto(
					chatId: command.Chat.Id,
					photo: new InputFileStream(generatedImageStream, "art.png"),
					replyMarkup: new InlineKeyboardMarkup(
						InlineKeyboardButton.WithUrl(
							text: "Generated by stability.ai SDXL",
							url: "https://stability.ai/stable-image"
						)
					),
					replyParameters: new ReplyParameters {
						MessageId = command.PromptMessageId
					},
					cancellationToken: cancellationToken
				);

				// Track thread
				telegramMessageCache.Add(
					NormalMessage.FromMessage(responseMessage, commandPriorityCategorizer)
				);
			}, logger);

			return default;
		}
	}
}
